services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    expose:
      - '9000'
    volumes:
      - app_data:/var/www/html
    depends_on:
      - db
    entrypoint: >
      /bin/sh -c "
        curl -L https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/latest/download/onlyoffice.tar.gz -o /tmp/onlyoffice.tar.gz &&
        tar -xzf /tmp/onlyoffice.tar.gz -C /var/www/html/apps/ &&
        php /var/www/html/occ app:enable onlyoffice ;
        php-fpm
      "

app-setup:
  container_name: app-setup
  image: nextcloud:fpm
  restart: "no"
  depends_on:
    - app
  volumes:
    - app_data:/var/www/html
  entrypoint: >
    /bin/sh -c "
      sleep 30 &&
      curl -L https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/latest/download/onlyoffice.tar.gz -o /tmp/onlyoffice.tar.gz &&
      tar -xzf /tmp/onlyoffice.tar.gz -C /var/www/html/apps/ &&
      php /var/www/html/occ app:enable onlyoffice
    "

  db:
    container_name: db-server
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    volumes:
      - db_data:/var/lib/postgresql/data

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    expose:
      - '80'
    volumes:
      - app_data:/var/www/html
    depends_on:
      - app

volumes:
  db_data:
  document_data:
  document_log:
  app_data:
